<?php
/**
 * Clear the cache of the updated node and the <front> page
 * Can also clear cache for the main page of the node -> taxonomy term
 * @author Timothée Moulin timothee.moulin@gmail.com
 * @version 1.0
 * @param I globally use the $node that is the current node given by Drupal
 */


/**
 * Implements hook_node_delete().
 */
function clearcache_node_delete($node)
{
	clearcache_clear($node);
}

/**
 * Implements hook_node_submit().
 * That's for all create new or update node.
 */
function clearcache_node_submit($node)
{
	clearcache_clear($node);
}

/**
 * Define what to clear
 */
function clearcache_clear($node)
{
	clearcache_for_home(); //clear the cache for the homepage
	clearcache_for_node($node->nid); //clear the cache for the updated node
	
	//clear the cache for the updated node rubrique field
	// please, replace the field_taxonomy with your own taxonomy field
	// clearcache_for_tax($node->field_taxonomy['und'][0]['tid']); 
}

function clearcache_for_home()
{
	clearcache_for('/');
}

function clearcache_for_node($nid=NULL)
{
	if ($nid==NULL)
		return false;
	$nodeurl = url('node/'.$nid);
	$cid = drupal_get_path_alias($nodeurl);
	clearcache_for($cid);
}

function clearcache_for_tax($tid=NULL)
{
	if ($tid==NULL)
		return false;
	$termurl = url('taxonomy/'.$tid);
	$cid = drupal_get_path_alias($termurl);
	// clearcache_for('/'.$cid);
	// dpm($cid);
}

function clearcache_for($cid=NULL)
{
	if ($cid==NULL)
	{
		cache_clear_all('*','cache_page',true);
		cache_clear_all('*','cache_view',true);
	}
	cache_clear_all($GLOBALS['base_root'].$cid, 'cache_page', false);
}